### ISSUE TITLE
Key character length is to long, its 64 characters when decryptor only accepts 32 characters

### ISSUE THREAD

**Issue by OvaFleming** [mmozeiko/aes-finder#27]
Key character length is to long, its 64 characters when decryptor only accepts 32 characters, when I use the aes finder I get aes 256 encryption and decryption keys which are 64 characters, am I doing something wrong?

**Comment by mmozeiko** [comment]
aes-256 key is 32-bytes long. And one byte is 2 hex characters. So aes-256 key will be 64 characters long.

**Comment by OvaFleming** [comment]
But the all the decryptors say that the the aes-256 key should be 32 characters long

**Comment by mmozeiko** [comment]
Who and where exactly are they saying that?

https://security.stackexchange.com/a/45334/81106
> An AES 256-bit key can be expressed as a hexadecimal string with 64 characters.

**Comment by OvaFleming** [comment]
https://www.devglan.com/online-tools/aes-encryption-decryption

When I give in the text to be decrypted, select aes 256 bit, then put in the secret and then click decrypt it says "length of secret key should be 32 for 256 bits key size".

**Comment by mmozeiko** [comment]
It seems they expect key to be entered as binary bytes, not as hex characters.
So when you enter '0' there, that is used as value 0x30. Or 'A' is 0x41.
That's why it expects same character count as byte count in AES key (AES-256 would expect 64 hex characters = 32 bytes).
I suggest to not use this tool.

**Comment by OvaFleming** [comment]
What tool would you recomend?

**Comment by mmozeiko** [comment]
openssl probably

`openssl enc -d -nopad -aes-256-cbc -in encrypted_file.bin -out decrytped_file.bin -K "keybytes" -iv "ivbytes"`

**Comment by OvaFleming** [comment]
I dont have an encrypted file and I dont have the iv, I only just want to decrypt encrpyted text.

**Comment by mmozeiko** [comment]
If you have encrypted text, then put it into file - and you will have encrypted file.
As for IV - you need to have it unless you're using aes-256-ecb method. That does not need iv, just skip `-iv` argument. But be sure you use same block mode (ECB, CBC, etc...) as encryption was using, otherwise results will be wrong.

**Comment by OvaFleming** [comment]
The encryption is GCM but I dont have the IV, is there anyway I can also get the IV? Also I read from here https://github.com/mmozeiko/aes-finder/issues/6#issuecomment-366063256 
you said that encrypted streams have the iv somewhere stored in it?

**Comment by mmozeiko** [comment]
Not automatically. It depends on how encryption algorithm was implemented. Sometimes they put it in front of encrypted stream. So if you have encrypted bytes, try using first 16 as IV value. But it really can be anything.

**Comment by OvaFleming** [comment]
I get this message when I use open ssl with -aes-256-gcm
enc: AEAD ciphers not supported

edit : never mind open ssl dosent have gcm

**Comment by OvaFleming** [comment]
I just libressl and it let me -aes-256-gcm then for gcm I had to use the first 12 bytes as the IV.
