### ISSUE TITLE
Efficiency Improvement Inquiry: Targeted Memory Scanning for AES Round Key Detection

### ISSUE THREAD

**Issue by halloweeks** [mmozeiko/aes-finder#41]
Could you clarify why your tool scans all memory regions to find round keys? If AES algorithms store round keys in either stack or heap memory, wouldn't it be more efficient to implement targeted scanning options for heap, stack, or all regions to speed up the process?

**Comment by mmozeiko** [comment]
It does that way because it was simpler to implement.
Changing to scan only specific memory regions is doable, but I think it's not a very useful improvement.
Instead I would recommend improving speed of AES scanning. Currently it runs ~30MB/s if I'm not mistaken, but that's because it's using software based AES. Instead it should use hw aes instructions, and that will easily increase speed 10x if not much more. Add in simple multithreading, and you'll be scanning all the memory regions in no time. Not much point of optimizing for scanning only stack or heap or something. Just scan everything, but fast.
