### ISSUE TITLE
ssl key

### ISSUE THREAD

**Issue by spm201** [mmozeiko/aes-finder#5]
Late in the sense  that attacker will be geting keys not used in the current session or something else.
attacker can record the communication using tools like wireshark and decrypt previous session and get
important information.  Keyloggers can be prevented by  not using keys of keyboard and using on screen keyboard provided by safe application. Ransomware is definitely an alternative but the person being attacked will know  about existence of malware (and they are done with malafide intention) whereas this kind of tool can be used  for ethical purpose or by law enforcing agencies.

**Comment by mmozeiko** [comment]
Please don't open new issue to post comment to existing discussion. Leave replies in issue #4.

Late in a sense that you computer is already compromised. If keylogger cannot be used because of on-screen keyboard, then this tool can simply capture screenshots/video to record entered keystrokes. No need for AES key finder. That's why you must trust software you run on your machine.
